FROM gcc:latest

RUN apt-get update && apt-get install -y wget git build-essential

WORKDIR /opt
RUN git clone https://github.com/emscripten-core/emsdk.git

RUN cd ./emsdk && \
  ./emsdk install latest && \
  ./emsdk activate latest

ENV PATH="$PATH:/opt/emsdk/upstream/emscripten/"

COPY . /wasm/code

WORKDIR /opt/wasm/compiled/c
RUN gcc -o helloworld /wasm/code/helloworld.c

WORKDIR /opt/wasm/compiled/html
RUN emcc -o helloworld.html /wasm/code/helloworld.c 

WORKDIR /opt/wasm/compiled/js
RUN emcc -o helloworld.js /wasm/code/helloworld.c

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]





# CMD ["emrun", "./helloworld.html"]

# EXPOSE 6931
