#brew install emscripten

version: "3"

dotenv:
  - ./.env

env:
  CONTAINER_BIN: docker
  CONTAINER_COMPOSE_BIN: " {{.CONTAINER_BIN}} compose "
  CONTAINER_FILE: "./ContainerFile"
  COMPOSE_FILE: "./compose.yaml"

tasks:
  default:
    desc: Shows this help message
    cmds:
      - task --list-all
    silent: true

  docker:build:
    desc: Build Docker image with GCC
    cmds:
      - docker build -t wasm-gcc -f ${CONTAINER_FILE} .
      - ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull wasm-helloworld
      
  compile:gcc:
    desc: Compile C to WebAssembly using GCC
    cmds:
      - gcc -o helloworld helloworld.c

  compile:emcc:html:
    desc: Compile C to WebAssembly using Emscripten (HTML)
    cmds:
      - emcc helloworld.c -o helloworld.html

  compile:emcc:js:
    desc: Compile C to WebAssembly using Emscripten (JS)
    cmds:
      - emcc helloworld.c -o helloworld.js

  docker:up:
    desc: Bring up Docker container
    deps:
      - docker:build
      - docker:down
    cmds:
      - ${CONTAINER_COMPOSE_BIN} up -d wasm-helloworld
      - echo
      - echo open http://localhost:6931/helloworld.html
      - echo

  docker:down:
    desc: Bring down Docker container
    cmds:
      - ${CONTAINER_COMPOSE_BIN} down

  run:local:
    desc: run the generated HTML file in the default web browser
    deps:
      - compile:emcc:html
    cmds:
      - emrun helloworld.html
